<?php
/*
 * Created on   : Thu Jan 02 2026
 * Author       : Daniel Jörg Schuppelius
 * Author Uri   : https://schuppelius.org
 * Filename     : Camt029DocumentBuilder.php
 * License      : AGPL-3.0-or-later
 * License Uri  : https://www.gnu.org/licenses/agpl-3.0.html
 */

declare(strict_types=1);

namespace CommonToolkit\FinancialFormats\Builders\ISO20022\Camt;

use CommonToolkit\FinancialFormats\Entities\ISO20022\Camt\Type29\CancellationDetails;
use CommonToolkit\FinancialFormats\Entities\ISO20022\Camt\Type29\Document;
use DateTimeImmutable;
use InvalidArgumentException;

/**
 * Builder for CAMT.029 Documents (Resolution of Investigation).
 * 
 * Creates responses to investigation requests (e.g. cancellation responses).
 * Typically generated by banks as a response to CAMT.055/056.
 * 
 * Verwendung:
 * ```php
 * $document = Camt029DocumentBuilder::create('ASGN-001')
 *     ->withAssignerAgent('COBADEFFXXX')
 *     ->withAssigneeAgent('DEUTDEFFXXX')
 *     ->forCase('CASE-001', 'COBADEFFXXX')
 *     ->withStatus('ACCP')
 *     ->addCancellationDetails($details)
 *     ->build();
 * ```
 * 
 * @package CommonToolkit\FinancialFormats\Builders\Camt
 */
final class Camt029DocumentBuilder {
    private string $assignmentId;
    private DateTimeImmutable $creationDateTime;
    private ?string $assignerAgentBic = null;
    private ?string $assignerPartyName = null;
    private ?string $assigneeAgentBic = null;
    private ?string $assigneePartyName = null;
    private ?string $caseId = null;
    private ?string $caseCreator = null;
    private ?string $investigationStatus = null;
    private ?string $investigationStatusProprietary = null;

    /** @var CancellationDetails[] */
    private array $cancellationDetails = [];

    private function __construct(string $assignmentId) {
        if (strlen($assignmentId) > 35) {
            throw new InvalidArgumentException('AssignmentId must not exceed 35 characters');
        }
        $this->assignmentId = $assignmentId;
        $this->creationDateTime = new DateTimeImmutable();
    }

    /**
     * Creates a new builder with assignment ID.
     */
    public static function create(string $assignmentId): self {
        return new self($assignmentId);
    }

    /**
     * Sets the creation timestamp (default: now).
     */
    public function withCreationDateTime(DateTimeImmutable $dateTime): self {
        $clone = clone $this;
        $clone->creationDateTime = $dateTime;
        return $clone;
    }

    /**
     * Sets the assigner agent (sending bank).
     */
    public function withAssignerAgent(string $bic): self {
        $clone = clone $this;
        $clone->assignerAgentBic = $bic;
        return $clone;
    }

    /**
     * Sets the assigner party name.
     */
    public function withAssignerPartyName(string $name): self {
        $clone = clone $this;
        $clone->assignerPartyName = $name;
        return $clone;
    }

    /**
     * Sets the assignee agent (receiving bank).
     */
    public function withAssigneeAgent(string $bic): self {
        $clone = clone $this;
        $clone->assigneeAgentBic = $bic;
        return $clone;
    }

    /**
     * Sets the assignee party name.
     */
    public function withAssigneePartyName(string $name): self {
        $clone = clone $this;
        $clone->assigneePartyName = $name;
        return $clone;
    }

    /**
     * Sets the case reference.
     */
    public function forCase(string $caseId, ?string $caseCreator = null): self {
        $clone = clone $this;
        $clone->caseId = $caseId;
        $clone->caseCreator = $caseCreator;
        return $clone;
    }

    /**
     * Sets the investigation status (code).
     * 
     * Common status codes:
     * - ACCP: Accepted (cancellation accepted)
     * - RJCT: Rejected (cancellation rejected)
     * - PDNG: Pending (in progress)
     * - CNCL: Cancelled
     */
    public function withStatus(string $statusCode): self {
        $clone = clone $this;
        $clone->investigationStatus = $statusCode;
        return $clone;
    }

    /**
     * Sets the investigation status (proprietary).
     */
    public function withProprietaryStatus(string $status): self {
        $clone = clone $this;
        $clone->investigationStatusProprietary = $status;
        return $clone;
    }

    /**
     * Adds cancellation details.
     */
    public function addCancellationDetails(CancellationDetails $details): self {
        $clone = clone $this;
        $clone->cancellationDetails[] = $details;
        return $clone;
    }

    /**
     * Adds multiple cancellation details.
     * 
     * @param CancellationDetails[] $details
     */
    public function addCancellationDetailsBulk(array $details): self {
        $clone = clone $this;
        $clone->cancellationDetails = array_merge($clone->cancellationDetails, $details);
        return $clone;
    }

    /**
     * Creates the CAMT.029 document.
     * 
     * @throws InvalidArgumentException if required fields are missing
     */
    public function build(): Document {
        $document = new Document(
            assignmentId: $this->assignmentId,
            creationDateTime: $this->creationDateTime,
            assignerAgentBic: $this->assignerAgentBic,
            assignerPartyName: $this->assignerPartyName,
            assigneeAgentBic: $this->assigneeAgentBic,
            assigneePartyName: $this->assigneePartyName,
            caseId: $this->caseId,
            caseCreator: $this->caseCreator,
            investigationStatus: $this->investigationStatus,
            investigationStatusProprietary: $this->investigationStatusProprietary
        );

        foreach ($this->cancellationDetails as $details) {
            $document->addCancellationDetails($details);
        }

        return $document;
    }

    // === Static Factory Methods ===

    /**
     * Creates a simple acceptance response.
     */
    public static function createAccepted(
        string $assignmentId,
        string $caseId,
        string $assignerBic,
        string $assigneeBic
    ): Document {
        return self::create($assignmentId)
            ->forCase($caseId)
            ->withAssignerAgent($assignerBic)
            ->withAssigneeAgent($assigneeBic)
            ->withStatus('ACCP')
            ->build();
    }

    /**
     * Creates a simple rejection response.
     */
    public static function createRejected(
        string $assignmentId,
        string $caseId,
        string $assignerBic,
        string $assigneeBic
    ): Document {
        return self::create($assignmentId)
            ->forCase($caseId)
            ->withAssignerAgent($assignerBic)
            ->withAssigneeAgent($assigneeBic)
            ->withStatus('RJCT')
            ->build();
    }
}
